version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ethglobal-2025-pi:latest
    container_name: ethglobal-2025-pi-app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py
    devices:
      - /dev/snd:/dev/snd
